### ISSUE TITLE
When deploying MMC, ability to specify a database for persisting events different from the default one.

### ISSUE THREAD

**Issue by nahuel-dallavecchia** [mulesoft-labs/cargo-mule-container#3]
This feature would need the following capabilities:
- Specification of JDBC driver and its deploy on lib folder.
- Replacement of tracking-applicationContext.xml and persistence.xml or at least update of the field regarding database connectivity, and OpenJPA log level.

**Comment by jeluard** [comment]
This plugin knows nothing about MMC or any specific application.
The only option you would have here is to rely on Java property values (see issue #1)
