### ISSUE TITLE
Ability to specify the name of the Mule instance to be started.

### ISSUE THREAD

**Issue by nahuel-dallavecchia** [mulesoft-labs/cargo-mule-container#4]
Currently the name of the Mule instance to be run can be specified by 

"-Dmule.serverId=<insert name here>" on Mule command line.

An application can use that name, alongside IP and port to identify themselves. In an environment were multiple instances of Mule are being run, it would be very useful (mainly for automation) to identify which apps are running in which Mule instance, using this simple method.

In fact, it would be good to have a general mechanism in order to be able to specify zero or more switches usually used on the command line.

**Comment by jeluard** [comment]
You can follow approach described in #1 to achieve this.
